version: '3.7'
services:
  sync:
    depends_on:
      - auth
      - chatd
      - confd
      - postgres
      - rabbitmq
    environment:
      TARGETS: "confd:9486 chatd:9304 auth:9497 postgres:5432 rabbitmq:5672"

  chatd:
    image: wazo-chatd-test
    volumes:
      - ./etc/wazo-chatd/conf.d/20-initialization.yml:/etc/wazo-chatd/conf.d/20-initialization.yml:ro
